# Generated by Django 3.2.16 on 2022-11-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0003_auto_20221106_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtaccumulate',
            name='borrower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtaccumulate',
            name='lender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL),
        ),
    ]
